### ISSUE TITLE
关于动车组交路查询的油猴脚本

### ISSUE THREAD

**Issue by Xxxxhx** [Arnie97/telecode#1]
12306改版导致脚本不能正常工作

**Comment by shulan-moe** [comment]
遇到同样问题。目前看来网页的结构并未大改，应该只是脚本URL匹配问题。由于新增的查询字符串导致脚本未激活。目前暂时通过手动在脚本的匹配URL后添加`*`解决，不过还是希望作者尽快更新w

**Comment by Arnie97** [comment]
是不是只有 https://kyfw.12306.cn/otn/leftTicket/init 后面新增了查询字符串？

更新当天我把我的相关项目都测了一遍，当时注意到这个变化了，但我自己测试能正常运行，就没修改。
现在看来，是我用的 ViolentMonkey 的行为与 `@match` 的标准实现不相同… Chrome Extensions、GreaseMonkey、TamperMonkey 都会匹配查询字符串部分。

**Comment by shulan-moe** [comment]
目前发现只有从新版首页点击的各项功能后会添加查询字符串，但是实际上在打开的网页中修改查询的数据并不会导致查询字符串变更，估计是12306系统功能还没有全部更新匹配完成。

顺带一提我这使用的是 TamperMonkey V4.7+Chrome 72.0.3602.2 不在结尾加`*`是无法匹配的

刚刚去翻了翻TamperMonkey的文档发现他的`@include` 这个给的link已经暂时无法查看，而`@match`的link里面也没有提到对URL查询字符串的处理问题，所以我对不同插件对查询字符串的处理也很是好奇umm

另外此项目有Chrome Extensions ？有在Chrome Web Store上架吗？之前没找到的说。
无论如何感谢您的贡献。
