### ISSUE TITLE
Dynamic Tracking 部分车次无法正确查询

### ISSUE THREAD

**Issue by hqy2000** [Arnie97/telecode#2]
**重现步骤**
1. 查询G1888次列车。
2. 查看历史。
3. 显示“加载失败”。

**原因**
服务器返回400错误。

**解决方法**
将查询服务器API请求中的字母大写，例如将 https://mpmp.ml/train/g1888 ，换为 https://mpmp.ml/train/G1888 ，即可正确查询。

**Comment by hqy2000** [comment]
另外这个问题仅会在查询框内输入小写字母时出现（如输入g1888）。如果原来查询的车次号就是大写字母（G1888），返回是正常的。个人猜测是将小写转大写时出现了同步上的问题？

浏览器环境：Chrome 75.0.3770.100

**Comment by Arnie97** [comment]
确认 bug。

**Comment by Arnie97** [comment]
感谢指出，已修复
